

spring:
    datasource:
      username: root
      password: 123456!QAZ2wsx#EDC
      url: jdbc:mysql://10.1.11.123:3306/obd_isuzu?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
      mapper-locations: classpath:mapping/*Mapper.xml
      type-aliases-package: ck.janko.entity